# Generated by Django 3.2.9 on 2022-08-26 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('template', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='任务名称', max_length=125)),
                ('status', models.BooleanField(choices=[(0, '关闭'), (1, '开启')], default=1, help_text='任务状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True)),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True)),
                ('callback_url', models.TextField(blank=True, default=None, help_text='回调接口', null=True)),
                ('callback_url_headers', models.TextField(blank=True, default='{}', help_text='接口header', null=True)),
                ('is_tmp', models.BooleanField(choices=[(0, 'tmp'), (1, 'formal')], default=0, help_text='任务是否为缓存状态')),
                ('show_dashboard', models.BooleanField(choices=[(0, 'false'), (1, 'true')], default=0, help_text='任务是否展示在dashboard')),
                ('user', models.ForeignKey(db_constraint=False, help_text='所属用户', on_delete=django.db.models.deletion.CASCADE, related_name='user_task', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='TaskConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='key', max_length=32)),
                ('task', models.ForeignKey(db_constraint=False, help_text='所属任务', on_delete=django.db.models.deletion.CASCADE, related_name='task_task_config', to='task.task')),
            ],
            options={
                'db_table': 'task_config',
            },
        ),
        migrations.CreateModel(
            name='TaskConfigItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(default=dict, help_text='配置项的值', max_length=255)),
                ('task', models.ForeignKey(db_constraint=False, help_text='任务', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_task_config_item', to='task.task')),
                ('task_config', models.ForeignKey(db_constraint=False, help_text='任务配置', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_config_task_config_item', to='task.taskconfig')),
                ('template', models.ForeignKey(db_constraint=False, help_text='模板', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_task_config_item', to='template.template')),
                ('template_config_item', models.ForeignKey(db_constraint=False, help_text='模板配置项', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_config_item_task_config_item', to='template.templateconfigitem')),
            ],
            options={
                'db_table': 'task_config_item',
            },
        ),
    ]
