# Generated by Django 3.2.9 on 2022-08-26 10:25

from django.db import migrations
import os

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
        ("api", "0002_auto_20220826_0811"),
    ]

    operations = [
        migrations.RunSQL(
            """
INSERT INTO antenna.task (id, name, status, create_time, update_time, callback_url, callback_url_headers, is_tmp, show_dashboard, user_id) VALUES (1, '初始任务', 1, '2022-08-17 14:27:50.425571', '2022-08-17 14:27:50.425608', null, '{}', 1, 1, 1);
INSERT INTO antenna.task_config (id, `key`, task_id) VALUES (1, 'KiG4', 1);
INSERT INTO antenna.task_config (id, `key`, task_id) VALUES (2, 'T9eF', 1);
INSERT INTO antenna.task_config (id, `key`, task_id) VALUES (3, 'x1Yh', 1);
INSERT INTO antenna.task_config (id, `key`, task_id) VALUES (4, 'LqhG', 1);
INSERT INTO antenna.task_config (id, `key`, task_id) VALUES (5, 'ya4I', 1);
INSERT INTO antenna.task_config (id, `key`, task_id) VALUES (6, 'QqHg', 1);
INSERT INTO antenna.task_config_item (id, value, task_id, task_config_id, template_id, template_config_item_id) VALUES (1, '{}', 1, 1, 1, 1);
INSERT INTO antenna.task_config_item (id, value, task_id, task_config_id, template_id, template_config_item_id) VALUES (2, '{}', 1, 2, 7, 9);
INSERT INTO antenna.task_config_item (id, value, task_id, task_config_id, template_id, template_config_item_id) VALUES (3, '{}', 1, 3, 2, 2);
INSERT INTO antenna.task_config_item (id, value, task_id, task_config_id, template_id, template_config_item_id) VALUES (4, '{}', 1, 4, 3, 3);
INSERT INTO antenna.task_config_item (id, value, task_id, task_config_id, template_id, template_config_item_id) VALUES (5, '{}', 1, 5, 4, 4);
INSERT INTO antenna.task_config_item (id, value, task_id, task_config_id, template_id, template_config_item_id) VALUES (6, '{}', 1, 5, 5, 4);
INSERT INTO antenna.task_config_item (id, value, task_id, task_config_id, template_id, template_config_item_id) VALUES (7, '{"path": "/etc/passwd"}', 1, 6, 6, 11);
"""
        ),
    ]
