# Generated by Django 3.2.9 on 2023-04-26 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0004_urltemplate'),
        ('task', '0002_auto_20220826_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskconfigitem',
            name='url_template',
            field=models.ForeignKey(db_column=False, help_text='链接模板', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_template_task_config_item', to='template.urltemplate'),
        ),
    ]
