# Generated by Django 3.2.9 on 2023-05-23 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0004_urltemplate'),
        ('task', '0003_taskconfigitem_url_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskconfigitem',
            name='url_template',
        ),
        migrations.AddField(
            model_name='taskconfig',
            name='url_template',
            field=models.ForeignKey(db_column=False, help_text='链接模板', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_template_task_config_item', to='template.urltemplate'),
        ),
    ]
