# Generated by Django 3.2.9 on 2022-08-26 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='模板文件名', max_length=125, unique=True)),
                ('title', models.CharField(default='默认模板名', help_text='模板对外名称', max_length=125, unique=True)),
                ('desc', models.TextField(blank=True, help_text='模板简介', null=True)),
                ('desc_url', models.URLField(blank=True, help_text='详细描述的地址', null=True)),
                ('author', models.CharField(default='58安全', help_text='模板作者', max_length=125)),
                ('type', models.IntegerField(choices=[(1, '监听'), (0, '利用')], default=1, help_text='模板类型')),
                ('choice_type', models.IntegerField(choices=[(1, '多选'), (0, '单选')], default=0, help_text='是否可以多选')),
                ('file_name', models.CharField(blank=True, help_text='文件名', max_length=36, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True)),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True)),
                ('is_private', models.IntegerField(choices=[(1, '公开'), (0, '私有')], default=1, help_text='开放类型')),
                ('payload', models.TextField(default='http://{domain}/{key}', help_text='利用代码实例')),
                ('user', models.ForeignKey(db_constraint=False, default=1, help_text='上传作者', on_delete=django.db.models.deletion.CASCADE, related_name='user_template', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'template',
            },
        ),
        migrations.CreateModel(
            name='TemplateConfigItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='配置项名称', max_length=125, unique=True)),
                ('config', models.JSONField(default=list, help_text='外部传递参数', max_length=125)),
                ('template', models.ForeignKey(db_constraint=False, help_text='所属模板', on_delete=django.db.models.deletion.CASCADE, related_name='template_template_config_item', to='template.template')),
            ],
            options={
                'db_table': 'template_config_item',
            },
        ),
    ]
