# Generated by Django 3.2.9 on 2022-08-26 10:26
# _*_ coding: utf-8 _*_
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("template", "0002_auto_20220826_1026.py"),
    ]

    operations = [
        migrations.RunSQL(
            """
INSERT INTO antenna.template (id, name, title, `desc`, desc_url, author, type, choice_type, file_name, create_time, update_time, is_private, payload, user_id) VALUES (8, 'FTP', 'FTP协议监听组件', '', '', 'bios000', 1, 0, 'ftplog.py', '2022-09-04 07:29:10.592067', '2022-09-05 22:11:12.907401', 1, 'ftp://{key}:123456@{domain}/antenna', 1);
INSERT INTO antenna.template (id, name, title, `desc`, desc_url, author, type, choice_type, file_name, create_time, update_time, is_private, payload, user_id) VALUES (9, 'HTTPS', 'HTTPS协议监听组件', '', '', 'bios000', 1, 0, 'httpslog.py', '2022-09-04 07:29:10.592067', '2022-09-05 22:11:12.907401', 1, 'https://{key}.{domain}', 1);
"""
        ),
        migrations.RunSQL(
            """
INSERT INTO antenna.template_config_item (id, name, config, template_id) VALUES (12, 'ftp_log', '[]', 8);
INSERT INTO antenna.template_config_item (id, name, config, template_id) VALUES (13, 'ftp_xxe_read_file', '["path"]', 6);
INSERT INTO antenna.template_config_item (id, name, config, template_id) VALUES (14, 'php_xxe_read_file', '["path"]', 6);
INSERT INTO antenna.template_config_item (id, name, config, template_id) VALUES (15, 'https_log', '[]', 9);
"""
        ),
    ]
