# Generated by Django 3.2.9 on 2023-04-26 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0003_template_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.TextField(default='http://{domain}/{key}', help_text='利用代码实例')),
                ('template', models.ForeignKey(db_constraint=False, help_text='所属模板', on_delete=django.db.models.deletion.CASCADE, related_name='template_url_template', to='template.template')),
            ],
            options={
                'db_table': 'template_url',
            },
        ),
    ]
