version: '3'
services:
  antenna:
    image: jongsx/antenna
    ports:
      - 8080:80
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      - MYSQL_HOST=mysql
  mysql:
    image: mysql
    restart: always
    command: [
      '--default-authentication-plugin=mysql_native_password',
      '--character-set-server=utf8',
      '--collation-server=utf8_unicode_ci'
    ]
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: antenna