version: '3'
services:
  unomi:
    image: jongsx/antenna
    ports:
      - 80:80
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql
    restart: always
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: antenna