# Generated by Django 3.2.9 on 2022-09-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.IntegerField(choices=[(1, 'HTTP'), (2, 'DNS'), (3, 'LDAP'), (4, 'RMI'), (5, 'FTP'), (6, 'MYSQL'), (7, 'HTTPS')], default=1, help_text='消息类型'),
        ),
    ]
