# Generated by Django 3.2.9 on 2022-09-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_alter_message_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='html',
            field=models.TextField(blank=True, help_text='接收内容', null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, help_text='自定义接收内容', null=True),
        ),
    ]
