# Generated by Django 3.2.9 on 2022-08-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='配置名', max_length=32)),
                ('type', models.IntegerField(choices=[(0, '平台配置'), (1, '协议配置')], default=0, help_text='配置类型')),
                ('value', models.CharField(blank=True, help_text='配置内容', max_length=32, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True)),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True)),
            ],
            options={
                'db_table': 'config',
            },
        ),
    ]
