# Generated by Django 3.2.9 on 2023-02-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20230206_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='type',
            field=models.IntegerField(choices=[(0, '平台配置'), (1, '协议配置'), (2, '邮件配置'), (3, '消息配置'), (4, 'DNS监听配置'), (5, 'RMI/LDAP监听配置'), (6, 'HTTPS监听配置'), (7, 'FTP监听配置')], default=0, help_text='配置类型'),
        ),
    ]
