# Generated by Django 3.2.9 on 2022-08-26 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='apikey', max_length=32)),
                ('update_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True)),
                ('user', models.ForeignKey(db_constraint=False, help_text='用户', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_key',
            },
        ),
    ]
