# Generated by Django 3.2.9 on 2022-08-26 08:11
import os

from django.db import migrations
from utils.helper import create_salt


def create_apikey(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    User = apps.get_model("auth", "User")
    root_name = os.environ.get('PLATFORM_ROOT_USER')
    user = User.objects.create(
        id=1,
        password="pbkdf2_sha256$260000$xGOtY8UIDmVOhMxxf97MrC$zyrByum510+7GTa/lr1WaVLNh+cbFzJuuxnM81OTYcw=",
        is_superuser=0,
        username=root_name,
        email=root_name,
        is_staff=1,
        is_active=1,
        last_login='2022-01-01 00:00:00'
    )

    ApiKey = apps.get_model("api", "ApiKey")
    # from modules.config.models import Config

    ApiKey.objects.create(
        key=create_salt(32),
        user=user,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_apikey),
    ]
