# Generated by Django 3.2.9 on 2023-02-21 15:28
import os

from django.contrib.auth.hashers import make_password
from django.db import migrations


class Migration(migrations.Migration):
    def update_user_password(apps, schema_editor):
        # We can't import the Person model directly as it may be a newer
        # version than this migration expects. We use the historical version.
        User = apps.get_model("auth", "User")
        # merge #56 初始化可自定义密码，感谢shadow1ng
        root_password = os.getenv("PLATFORM_ROOT_PASSWORD")
        sha256_pwd = make_password(root_password, None, 'pbkdf2_sha256')
        User.objects.filter(id=1).update(password=sha256_pwd)

    dependencies = [
        ('api', '0002_auto_20220826_0811'),
    ]

    operations = [
        migrations.RunPython(update_user_password),
    ]
